### ISSUE TITLE
MiKo_5001 cast exception

### ISSUE THREAD

**Issue by RalfKoban** [RalfKoban/MiKo-Analyzers#375]
```c#
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.MemberAccessExpressionSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax'.
   at MiKoSolutions.Analyzers.Rules.Performance.MiKo_5001_CodeFixProvider.GetUpdatedSyntax(Document document,SyntaxNode syntax,Diagnostic diagnostic)
   at MiKoSolutions.Analyzers.Rules.MiKoCodeFixProvider.ApplyDocumentCodeFixAsync(Document document,SyntaxNode root,SyntaxNode syntax,Diagnostic diagnostic)
   at MiKoSolutions.Analyzers.Rules.MiKoCodeFixProvider.<>c__DisplayClass21_0.<CreateCodeFix>b__1(CancellationToken _)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.DocumentChangeAction.GetChangedDocumentAsync(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavorAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavorsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)```

**Comment by RalfKoban** [comment]
```
				TestContext.Logger.Debug($"Running step {x} out of {DebugStepsCount} Steps");
```

**Comment by RalfKoban** [comment]
Already fixed
